# Source https://alacritty.org/config-alacritty.html

import = ["~/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "BoldItalic"

[shell]
program = "/opt/homebrew/bin/fish"
args = ["--login"]

[window]
dimensions.columns = 120
dimensions.lines = 40
resize_increments = true
dynamic_padding = true
padding.x = 4
padding.y = 4
decorations = "full"
dynamic_title = false
title = "Dev As Life"

[scrolling]
history = 50000

[selection]
save_to_clipboard = true

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = true
